### ISSUE TITLE
Support of Graph

### ISSUE THREAD

**Issue by martinfleis** [pysal/esda#294]
As a follow-up on #293, I checked what needs to happen elsewhere with this outcome:

**Works with minor changes**
- [x] Geary #296

**Works with minor refactor**
- [x] G #326
- [x] Moran #293 

**Need a re-implementation or a fallback to W**
- [x] Gamma #326 
- [x] G_Local #326
- [x] Geary_Local #296
- [x] Geary_Local_MV #296
- [x] Join_Counts #295 
- [x] Join_Counts_Local #295 
- [x] Join_Counts_Local_* #295 
- [x] LOSH #327
- [x] Silhouettes #327

Not as great as I hoped for. I still think it won't be a too complex refactoring to support Graph in stuff like Gamma or Join_Counts but we'll need to be more invasive that I was in #293 to get a native support.

My main question is _how acceptable is an internal fallback to W?_ For a reference, conversion of Queen contiguity of `geoda.us_sdoh` (72k polygons) to W takes 1.75 s ± 27.2 ms on my M1. Which is considerable, given that getting Moran takes `1.45 s ± 36.2 ms` with Graph and `3.17 s ± 43.1 ms` if I include `to_W`.
