### ISSUE TITLE
migrate from `unittest` to `pytest` structure.

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#323]
Lots of tests in the `esda` suite still actively use `unittest` -- we should migrate all those to the modern `pytest` structure. 

* [x] `test_adbscan.py` – https://github.com/pysal/esda/pull/343
* [x] `test_crand.py` – [#363](#363)
* [x] `test_gamma.py` – [#363](#363)
* [x] `test_geary.py` – [#363](#363)
* [x] `test_getisord.py` – [#363](#363)
* [x] `test_join_counts.py` – [#363](#363)
* [x] `test_lee.py` – [#366](#366)
* [x] `test_ljc_bv.py` – [#366](#366)
* [x] `test_ljc_mv.py` – [#366](#366)
* [x] `test_ljc.py` – [#366](#366)
* [x] `test_local_geary_mv.py` – [#366](#366)
* [x] `test_local_geary.py` – [#366](#366)
* [x] `test_losh.py` – [#366](#366)
* [x] `test_map_comparison.py` – [#367](#367)
* [x] `test_mixture_smoothing.py` – [#367](#367)
* [x] `test_moran.py` – [#367](#367)
* [x] `test_shape.py` – [#367](#367)
* [x] `test_silhouette.py` – [#367](#367)
* [x] `test_smaup.py` – [#367](#367)
* [x] `test_smoothing.py` – [#370](#370)
* [x] `test_topo.py` – https://github.com/pysal/esda/pull/341
* [x] `test_util.py` – https://github.com/pysal/esda/pull/341

**Comment by jGaboardi** [comment]
@martinfleis 

Same Q for this issue --> https://github.com/pysal/esda/issues/308#issuecomment-2220663719

**Comment by martinfleis** [comment]
Same answer :)

**Comment by jGaboardi** [comment]
This is (of course) turning out to be a far more in-depth task than anticipated (when am I going to learn?). Going to spilt this out by file or groups of files.

xref #340

**Comment by jGaboardi** [comment]
* [ ] `test_adbscan.py`
* [ ] `test_crand.py`
* [ ] `test_gamma.py`
* [ ] `test_geary.py`
* [ ] `test_getisord.py`
* [ ] `test_join_counts.py`
* [ ] `test_lee.py`
* [ ] `test_ljc_bv.py`
* [ ] `test_ljc_mv.py`
* [ ] `test_ljc.py`
* [ ] `test_local_geary_mv.py`
* [ ] `test_local_geary.py`
* [ ] `test_losh.py`
* [ ] `test_map_comparison.py`
* [ ] `test_mixture_smoothing.py`
* [ ] `test_moran.py`
* [ ] `test_shape.py`
* [ ] `test_silhouette.py`
* [ ] `test_smaup.py`
* [ ] `test_smoothing.py`
* [ ] `test_topo.py`
* [ ] `test_util.py`
