### ISSUE TITLE
format & lint `tests/*`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#335]
Follow up #332 with a comb through the `tests/` directory for linting and formatting. -- xref #323 

* [x] `test_adbscan.py` – https://github.com/pysal/esda/pull/343
* [x] `test_crand.py` – [#363](#363)
* [x] `test_gamma.py` – [#363](#363)
* [x] `test_geary.py` – [#363](#363)
* [x] `test_getisord.py` – [#363](#363)
* [x] `test_join_counts.py` – [#363](#363)
* [x] `test_lee.py` – [#366](#366)
* [x] `test_ljc_bv.py` – [#366](#366)
* [x] `test_ljc_mv.py` – [#366](#366)
* [x] `test_ljc.py` – [#366](#366)
* [x] `test_local_geary_mv.py` – [#366](#366)
* [x] `test_local_geary.py` – [#366](#366)
* [x] `test_losh.py` – [#366](#366)
* [x] `test_map_comparison.py` – [#367](#367)
* [x] `test_mixture_smoothing.py` – [#367](#367)
* [x] `test_moran.py` – [#367](#367)
* [x] `test_shape.py` – [#367](#367)
* [x] `test_silhouette.py` – [#367](#367)
* [x] `test_smaup.py` – [#367](#367)
* [x] `test_smoothing.py` – [#370](#370)
* [x] `test_topo.py` – https://github.com/pysal/esda/pull/341
* [x] `test_util.py` – https://github.com/pysal/esda/pull/341
* [x]  update `pyproject.toml` – [#370](#370)
